CREATE TABLE IF NOT EXISTS homepage_setting (
  setting_id BIGINT NOT NULL PRIMARY KEY,
  hero_scenes_json TEXT NULL,
  story_kicker VARCHAR(80) NOT NULL,
  story_title VARCHAR(160) NOT NULL,
  story_description VARCHAR(700) NOT NULL,
  signature_kicker VARCHAR(80) NOT NULL,
  signature_title VARCHAR(160) NOT NULL,
  store_kicker VARCHAR(80) NOT NULL,
  store_title VARCHAR(160) NOT NULL,
  store_description VARCHAR(360) NOT NULL,
  news_kicker VARCHAR(80) NOT NULL,
  news_title VARCHAR(160) NOT NULL,
  reservation_kicker VARCHAR(80) NOT NULL,
  reservation_title VARCHAR(160) NOT NULL,
  reservation_description VARCHAR(700) NOT NULL,
  featured_store_ids VARCHAR(240) NULL,
  featured_news_ids VARCHAR(240) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO homepage_setting (
  setting_id,
  hero_scenes_json,
  story_kicker,
  story_title,
  story_description,
  signature_kicker,
  signature_title,
  store_kicker,
  store_title,
  store_description,
  news_kicker,
  news_title,
  reservation_kicker,
  reservation_title,
  reservation_description,
  featured_store_ids,
  featured_news_ids
) VALUES (
  1,
  '[{"label":"夜席","imageKey":"home","imageUrl":null,"eyebrow":"Xuri Washoku","title":"敘日和食","lines":["「敘」是敘舊，是放下手機後的深度對談","「日」是時光，是歲月淬鍊出的滋味"]},{"label":"旬味","imageKey":"salmonSashimi","imageUrl":null,"eyebrow":"Seasonal Sashimi","title":"今日旬味","lines":["低溫配送的魚身甜度","讓聚餐從第一口開始慢下來"]},{"label":"吧台","imageKey":"reservation","imageUrl":null,"eyebrow":"Chef Counter","title":"一席之間","lines":["從訂位到上菜都有清楚節奏","把用餐體驗交給剛好的時間"]}]',
  'Xuri Table',
  '把忙碌留在門外，讓一餐飯重新有時間感。',
  '敘日把和食做成日常可以靠近的樣子：保留刺身、握壽司、鍋物與甘味的細節，也把訂位、門市與菜單動線整理成清楚的節奏。從進門、點餐到結帳，每個環節都為聚餐的人服務。',
  'Seasonal Selection',
  '今天想吃的，不只是一份菜單。',
  'Locations',
  '今晚坐哪一間敘日。',
  '依城市、交通與用餐情境挑選門市，讓前往餐桌這件事也輕鬆。',
  'News',
  '近期公告與餐期更新。',
  'Reservation',
  '從今天的城市，選一張剛好的桌。',
  '選擇門市、日期、人數與時段後，系統會依席位與營業狀態回覆可訂選項。團體聚餐或特殊需求，也可以在訂位備註中先告訴店長。',
  NULL,
  NULL
) ON DUPLICATE KEY UPDATE setting_id = setting_id;
