CREATE TABLE IF NOT EXISTS faq_item (
  faq_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  question VARCHAR(180) NOT NULL,
  answer TEXT NOT NULL,
  keywords VARCHAR(320) NULL,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_faq_question (question),
  INDEX idx_faq_public (is_deleted, status, category, is_featured, sort_order),
  INDEX idx_faq_admin (is_deleted, is_featured, sort_order)
);

INSERT INTO faq_item
  (category, status, question, answer, keywords, is_featured, sort_order, is_deleted)
VALUES
  ('RESERVATION', 'PUBLISHED', '訂位最早可以預約多久之後的日期？',
   '線上訂位開放未來 30 天內的餐期。熱門餐期建議提前安排，若指定時段額滿，可改選相近門市或其他時段。',
   '訂位,預約,30天,一個月,熱門餐期,時段', 1, 10, 0),
  ('RESERVATION', 'PUBLISHED', '訂位需要在幾點前抵達？',
   '請依訂位時間準時抵達。若會晚到，建議先聯繫門市；座位通常會保留 10 分鐘，實際安排仍依當日候位狀況與門市說明為準。',
   '遲到,保留,抵達,候位,10分鐘,門市', 1, 20, 0),
  ('RESERVATION', 'PUBLISHED', '可以修改訂位人數或時間嗎？',
   '可於訂位紀錄中查看是否仍可調整。若餐期已額滿、接近用餐時間或涉及訂金，建議直接聯繫門市協助確認。',
   '修改訂位,改時間,改人數,訂位紀錄,額滿', 0, 30, 0),
  ('RESERVATION', 'PUBLISHED', '大人數或包廂訂位要怎麼預約？',
   '8 人以上、包廂或特殊餐期建議提前洽詢門市。門市會依座位配置、餐期人流與是否需要訂金，回覆可預約時段。',
   '大人數,包廂,多人訂位,特殊餐期,門市洽詢', 0, 40, 0),
  ('DEPOSIT', 'PUBLISHED', '哪些訂位需要支付訂金？',
   '特殊餐期、包廂、大人數或高需求時段可能需要支付訂金。系統會在訂位流程中顯示是否需付訂金與付款期限。',
   '訂金,付款期限,包廂,大人數,特殊餐期', 1, 50, 0),
  ('DEPOSIT', 'PUBLISHED', '訂金付款期限是多久？',
   '若訂位需要訂金，請依頁面顯示的期限完成付款。逾期未付款時，系統可能釋出座位供其他顧客預約。',
   '訂金期限,付款期限,逾期,釋出座位,付款', 0, 60, 0),
  ('DEPOSIT', 'PUBLISHED', '取消訂位後訂金可以退嗎？',
   '符合取消期限的訂位可依原付款方式辦理退款；若已超過取消期限、未到或臨時取消，訂金規則會依該餐期公告處理。',
   '取消,退款,訂金退還,未到,no show', 1, 70, 0),
  ('DEPOSIT', 'PUBLISHED', '沒有準時支付訂金會怎麼樣？',
   '未於期限內付款的訂位不會完成保留。若仍想用餐，可重新選擇目前可預約的門市、日期與時段。',
   '未付款,訂金,保留,重新訂位,逾期', 0, 80, 0),
  ('ORDER', 'PUBLISHED', '可以先線上點餐再到店用餐嗎？',
   '目前點餐功能支援依門市菜單建立訂單。內用訂單需選擇門市與桌位；外帶訂單可不指定桌位，實際供應品項依各門市設定為準。',
   '點餐,內用,外帶,桌位,門市菜單', 1, 90, 0),
  ('ORDER', 'PUBLISHED', '可以外帶點餐嗎？',
   '可以。外帶訂單可選擇支援外帶的門市與供應品項，完成付款後依頁面或門市通知的時間取餐。',
   '外帶,點餐,取餐,付款,門市', 1, 100, 0),
  ('ORDER', 'PUBLISHED', '為什麼不同門市看到的菜單不一樣？',
   '菜單會依門市供應、時段、庫存與營業狀態顯示。若某品項暫停供應，頁面會以當下可販售內容為準。',
   '菜單,門市菜單,庫存,暫停供應,品項', 0, 110, 0),
  ('PAYMENT', 'PUBLISHED', '付款方式有哪些？',
   '系統支援信用卡與 Line Pay 等付款流程。部分門市現場付款、發票與退款處理方式，請依結帳頁面與門市說明為準。',
   '付款,信用卡,Line Pay,發票,退款', 0, 120, 0),
  ('PAYMENT', 'PUBLISHED', '發票如何開立或查詢？',
   '線上付款完成後，發票資訊會依結帳頁面填寫內容處理。若需統編或載具，請在付款前確認資料正確。',
   '發票,統編,載具,付款,電子發票', 0, 130, 0),
  ('PAYMENT', 'PUBLISHED', '退款通常多久會入帳？',
   '退款送出後會依原付款方式與銀行作業時間入帳。若超過常見處理時間仍未收到，可提供訂單資訊請客服協助查詢。',
   '退款,入帳,信用卡,Line Pay,訂單資訊', 0, 140, 0),
  ('STORE', 'PUBLISHED', '如何查詢各門市營業狀態？',
   '可到分店資訊頁查看門市位置、交通方式、營業狀態與特色標籤。若門市暫停營業，系統會避免建立不適用的訂位或點餐流程。',
   '門市,營業狀態,交通,分店資訊,暫停營業', 1, 150, 0),
  ('STORE', 'PUBLISHED', '門市附近可以停車嗎？',
   '各門市交通與停車條件不同，建議先查看分店資訊頁的交通說明。商場門市請以商場停車與折抵規則為準。',
   '停車,交通,分店資訊,商場,折抵', 0, 160, 0),
  ('STORE', 'PUBLISHED', '臨時公休或營業異動會怎麼通知？',
   '若遇設備維護、天候或特殊營運調整，門市狀態會同步更新；已成立的訂位或訂單，會依留存聯絡資料通知。',
   '公休,營業異動,維護,通知,門市狀態', 0, 170, 0),
  ('MEMBER', 'PUBLISHED', '一定要登入會員才能訂位或點餐嗎？',
   '一般訂位與 demo 點餐流程可未登入使用；登入會員後可查看個人資料、訂位紀錄與消費紀錄，後續也能累積會員服務。',
   '會員,登入,訂位紀錄,消費紀錄,個人資料', 0, 180, 0),
  ('MEMBER', 'PUBLISHED', '登入後可以查看哪些紀錄？',
   '會員可查看個人資料、訂位紀錄、訂單與付款狀態。若使用不同電話或信箱建立紀錄，請以當次留存資料查詢。',
   '會員,訂位紀錄,訂單紀錄,付款狀態,個人資料', 0, 190, 0),
  ('SERVICE', 'PUBLISHED', '有特殊需求或過敏資訊要怎麼告知？',
   '建議在訂位備註中先寫明需求，例如兒童椅、包廂、慶生或過敏資訊。門市會依現場條件協助安排，實際結果以門市回覆為準。',
   '過敏,兒童椅,包廂,慶生,備註,特殊需求', 1, 200, 0),
  ('SERVICE', 'PUBLISHED', '可以攜帶寵物或外食嗎？',
   '餐廳以現場用餐品質與食品安全為優先，寵物、外食與蛋糕等規則依各門市條件辦理。建議訂位前先與門市確認。',
   '寵物,外食,蛋糕,食品安全,門市確認', 0, 210, 0),
  ('SERVICE', 'PUBLISHED', '兒童椅或慶生服務可以先備註嗎？',
   '可以在訂位備註先提出需求。兒童椅、慶生安排與座位配置數量有限，門市會依現場狀況協助保留。',
   '兒童椅,慶生,備註,座位配置,特殊需求', 0, 220, 0)
ON DUPLICATE KEY UPDATE
  category = VALUES(category),
  status = VALUES(status),
  answer = VALUES(answer),
  keywords = VALUES(keywords),
  is_featured = VALUES(is_featured),
  sort_order = VALUES(sort_order),
  is_deleted = VALUES(is_deleted);
